### ISSUE TITLE
Convertir les "/"  et "\" des scripts à la lecture du calculator.xml suivant l'OS

### ISSUE THREAD

**Issue by nchabalier** [Funz/funz-calculator#11]

**Comment by yannrichet** [comment]
? add .replace("/",File.separator).reaplce("\\",File.separator) in
https://github.com/Funz/funz-calculator/blob/c7c7bf8a38932b570955ad9c842a1421055d24be/src/main/java/org/funz/calculator/plugin/DefaultCodeLauncher.java#L239
